name: Notify Discord on Push or Merge

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord notification
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "$(jq -n --arg content "Changes in **${{ github.repository }}**\n
        **Commit by:** ${{ github.actor }}\n
        **Message:** ${{ github.event.head_commit.message }}\n
        **[View Commit](${{ github.event.head_commit.url }})**" \
        '{"content":$content}')" \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
