name: Notify Discord on Push or Merge

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    types: [closed]

jobs:
  # The workflow job name
  discord-notifier:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sequence of tasks
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.WEBHOOKS_URL }}
